fn main() {
    // Keep in sync with lib.rs invoke_handler — `npm run verify:acl` fails the build if not.
    tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(
            tauri_build::AppManifest::new().commands(&[
                "get_config",
                "save_config",
                "toggle_launcher",
                "dismiss_launcher",
                "cli_exec",
                "cli_exec_term",
                "cli_open",
                "cli_home",
                "cli_search_files",
                "sys_stats",
                "pty_open",
                "pty_write",
                "pty_resize",
                "pty_is_alive",
                "pty_close",
                "media_now",
                "media_play_pause_cmd",
                "media_next_cmd",
                "media_previous_cmd",
                "get_runtime_status",
                "open_log_folder",
                "list_catalog",
                "ack_catalog",
                "hide_catalog_entry",
                "get_desktop_layout",
                "toggle_desktop_surface",
                "open_desktop_surface",
                "close_desktop_surface",
                "show_launcher_seeded",
                "shell_show_desktop",
            ]),
        ),
    )
    .expect("failed to run tauri-build");
}
